apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction-deployment
  labels:
    app: churn-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-prediction
  template:
    metadata:
      labels:
        app: churn-prediction
    spec:
      containers:
      - name: churn-prediction-container
        image: churn-prediction-image:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: churn-prediction-service
spec:
  type: LoadBalancer
  selector:
    app: churn-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
