Dataset:
  data_dir: cleaned_data:v0
  file_name: cleaned_train.csv

LogisticRegression: 
  _target_: sklearn.linear_model.LogisticRegression
  penalty: l1
  C: 0.422
  random_state: 42
  solver: saga
  max_iter: 100

RandomForest:
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100
  criterion: entropy
  max_depth: 12
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  bootstrap: True
  n_jobs: -1
  random_state: 42
  max_samples: 0.8
